### ISSUE TITLE
[Suggestions] For July

### ISSUE THREAD

**Issue by quxios** [quasixi/Quasi-MV-Master-Demo#3]
Every month I will open a discussion where you may recommend plugins, addons, apps, or tutorials that you want me to create. This discussion will be closed in the middle of the month. A poll will be created for the second half of the month filled with approved requests. At the end of the month I will pick the top 1 or more requests and create them in the following month.

**Requests Submission deadline:** June 17, 2016 around noon.

Feel free to request anything. Anything that I think can be created under a month will be approved.

_\* If you are a Patreon supporter of Rank 2 or higher, send me a message on Patreon with your github user name so I can confirm who you are. Patreon suggestions will have a +1 to their suggestion when voting. When there is a tie and one is a Patreon suggestion, the Patreon suggestion will take priority._

**Approved**
- Item categories [matthew30903]
- Sprite wave effect [TheGamedawg]

**Maybe**
- Random Dungeon Generator [matthew30903]

**Comment by quxios** [comment]
Ops patreon link was redirecting to the wrong Issue.

Moving July suggestions from February Suggestions:
**matthew30903**

> For the July poll I would like to bring back up the dungeon generator idea. There is currently none that are stable or customizable enough to be useful and I could see most games finding one useful. I would be using the one that Kai Monkey's from VX Ace as an example.
> 
> If that is too much for a month's time, a plugin that give more item categories in the menu using either notetags or an external file for keeping track of what items are in what category would be great. Though Yanfly comparability with both the menu seen and the instanced items would be needed for most people. I do not know how hard that would be.
> 
> Thank you for all your hard work.

The item categories is approved, it was actually something I was going to work on sometime soon to go along with my recently released item scene.
As for the random dungeon generator. I've been tempted to create it lately, but it probably will be too long. But I'll take a look at that VXA script to see what they did, my idea might just be over complicating what needs to be done.

**Cats777**

> All I really want is party AI for QuasiABS.

Sorry, that's not something I'll approve. It won't take much work, but I just really don't like followers in MV and don't want to work with / on them. But I will be working on fixing the built in AI so it doesn't only go after / target the player and instead go after the biggest threat.

**Comment by TheGamedawg** [comment]
Hey Quasi, it's me from Twitter.  I"ve been looking for a particular plugin for the longest time that I know existed back in VX Ace, but I haven't found a recreation for for MV.  I was wondering if I could request it.  I explained exactly what I'm looking for on the forums and on the subreddit but no one seems to have an answer.  I'll copy my text from there and see if you'd be interested.

"
You guys know those wavy battle backgrounds in games like Earthbound? I was wondering is anyone has recreated something like that in MV.

I remember seeing a game called Hylics do exactly what I'm trying to do back in VX Ace so I'd imagine it would be very possible. This is a trailer for the game, watch the backgrounds during the battles to see what kind of effect I'm looking for. I was wondering if something like this exists for MV yet. And of not, how I would go about creating it.

https://www.youtube.com/watch?v=TgNUgeEryCM
"

So yeah, hopefully you can help!  Thanks!

**Comment by quxios** [comment]
As I mentioned on twitter, this is something I can approve!

Thanks for the suggestion!

**Comment by Mukar** [comment]
Hi Quasi! For the July poll, I was wondering if you planned on finishing your Tactical Battle System for MV and if it would work with multiple characters in your party. Seeing as there's currently no TBS systems for MV yet, yours could be the first! :D

**Comment by quxios** [comment]
I never started on a TBS for MV. It's also not something I can approve of here, since it's something that can take more then a month to complete. But it is listed as a goal in my Patreon, so once that goal is reached I will start working on a TBS.

**Comment by quxios** [comment]
Closing this up now.

But there will be no poll since there wasn't much submissions. Instead I'll just start working on the ones that were approved 2 weeks earlier.
